Question 1: What is a Support Vector Machine (SVM), and how does it work?

Answer: A Support Vector Machine (SVM) is a supervised machine learning algorithm used for classification and regression tasks.
Its main goal is to find the best boundary (hyperplane) that separates different classes in the feature space.
SVM works by mapping data to a high-dimensional feature space so that data points can be categorized, even when the data are not otherwise linearly separable. A separator between the categories is found, then the data are transformed in such a way that the separator could be drawn as a hyperplane. Following this, characteristics of new data can be used to predict the group to which a new record should belong.For example: Imagine a dataset in which the data points fall into two different categories. The two categories can be seperated with a curve. After the transformation, the boundary between the two categories can be defined by a hyperplane. The mathematical function used for the transformation is known as the kernel function. SVM supports linear, polynomial, radial bias function, sigmoid function kernel types.

Question 2: Explain the difference between Hard Margin and Soft Margin SVM.
Answer: Suppose we have data points that we want to classify into two groups. When the data is linearly separable, and we don't want to have any misclassifications that's why we use SVM with a hard margin. However, when a linear boundary is not feasible, or we want to allow some misclassifications in the hope of achieving better generality, we can opt for a soft margin for our classifier.
1. SVM with Hard Margin: In a hard margin SVM, the objective is to identify a hyperplane that completely separates data points belonging to different classes, ensuring a clear demarcation with the utmost margin width possible. This margin is the distance between the hyperplane and the nearest data point, also known as the support vectors.
The hyperplane equation plays a crucial role in hard margin SVMs because it defines the boundary that separates the classes. Ideally, we want this boundary to have a maximum margin from the nearest data points of each class. The objective function in hard margin SVM aims to find the weight vector and bias term that maximize this margin while ensuring that all data points are correctly classified. The decision boundary is solely determined by these support vectors, and any data points falling on the wrong side of the hyperplane contribute to the margin violation. Mathematically, for a linearly seperable dataset, the decision function of a hard margin SVM can be expressed as:
        yi(wTx + b) > 1
  where, x is the weight vector perpendicular to the plane.
  w is the weight of feature vector
  b is the bias term
The decision boundary is determined by the hyperplane equation
          wTx + b = 0
This equation essentially states that any data point lying on the hyperplane satisfies this equation. In other words, the dot product of the feature vector and the weight vector, shifted by the bias term, equals zero for points on the decision boundary.
      margin = 1/ |w|

2. SVM with a Soft Margin: Soft Margin SVM introduces flexibility by allowing some margin violations (misclassifications) to handle cases where the data is not perfectly separable. Suitable for scenarios where the data may contain noise or outliers. It Introduces a penalty term for misclassifications, allowing for a trade-off between a wider margin and a few misclassifications.

Soft margin SVM allows for some margin violations, meaning that it permits certain data points to fall within the margin or even on the wrong side of the decision boundary. This adaptability is managed by a factor called C, also called the "regularization parameter," which helps find a balance between making the gap as big as possible and reducing mistakes in grouping things.
Mathematically, decision function of a soft margin SVM can be defined as:
    yi(wTxi + b) > 1 - margin violation
  where, yi is the target variable

1/2|w|2 + C summation of Ni*margin violation

The equation combines the objectives of maximizing the margin (represented by the first term) and minimizing the penalty for margin violations (represented by the second term). The regularization parameter (C) controls the trade-off between these objectives. A higher C value prioritizes a wider margin, even if it allows some misclassifications. Conversely, a lower C value allows for more margin violations to achieve a smoother
decision boundary.

Question 3: What is the Kernel Trick in SVM? Give one example of a kernel and
explain its use case.

Answer:The kernel trick is a method used in SVMs to enable them to classify non-linear data using a linear classifier. By applying a kernel function, SVMs can implicitly map input data into a higher-dimensional space where a linear separator (hyperplane) can be used to divide the classes. This mapping is computationally efficient because it avoids the direct calculation of the coordinates in this higher space.
Radial Bias Function: The RBF kernel is the most widely used kernel in SVM. It creates non linear combination of features to bring your feature in higher dimension. The formula of RBF kernel is:
f(x1,x2) = e^-(||x1-x2||/ 2sigma^2)
where, ||x1-x2|| is euclidian distance between two point x1 and x2.
sigma  is variance/ hyperparameter.
Use case: RBF is used whenever the data in the radial format or curve format, can segregate using RBF function.

Question 4: What is a Naive Bayes Classifier, and why is it called “naïve”?

Answer: Naive Bayes is a classification algorithm that uses probability to predict which category a data point belongs to, assuming that all features are independent.The main idea behind the Naive Bayes classifier is to use Bayes' Theorem to classify data based on the probabilities of different classes given the features of the data. It is used mostly in high-dimensional text classification
- The Naive Bayes Classifier is a simple probabilistic classifier and it has very few number of parameters which are used to build the ML models that can predict at a faster speed than other classification algorithms.
- It is a probabilistic classifier because it assumes that one feature in the model is independent of existence of another feature. In other words, each feature contributes to the predictions with no relation between each other.
- Naïve Bayes Algorithm is used in spam filtration, Sentimental analysis, classifying articles and many more.

It is named as "Naive" because it assumees the presence of one feature doesnot affect other features.

Question 5: Describe the Gaussian, Multinomial, and Bernoulli Naïve Bayes variants. When would you use each one?

Answer:
Gaussian Naive Bayes: In Gaussian Naive Bayes, continuous values associated with each feature are assumed to be distributed according to a Gaussian distribution. A Gaussian distribution is also called Normal distribution When plotted, it gives a bell shaped curve which is symmetric about the mean of the feature values.

Multinomial Naive Bayes: It is used when features represent the frequency of terms (such as word counts) in a document. It is commonly applied in text classification, where term frequencies are important.

Bernoulli Naive Bayes: It deals with binary features, where each feature indicates whether a word appears or not in a document. It is suited for scenarios where the presence or absence of terms is more relevant than their frequency. Both models are widely used in document classification tasks.

Multinomial and Bernoulli Naive Bayes is used for text data in NLP.

Question 10: Imagine you're working as a data scientist for a company that handles email communications.
Your task is to automatically classify emails as Spam or Not Spam. The emails may contain:
- Text with diverse vocabulary
- Potential class imbalance (far more legitimate emails than spam)
- Some incomplete or missing data

Explain the approach you would take to:
- Preprocess the data (e.g. text vectorization, handling missing data)
- Choose and justify an appropriate model (SVM vs. Naïve Bayes)
- Address class imbalance
- Evaluate the performance of your solution with suitable metrics
And explain the business impact of your solution.

Answer:
Data Preprocessing: Under this step you can handle missing data like dropping the rows which contains missing emails, clean the text like: convert it into lower case, remove punctuations,HTML tags, and special characters,and extract the features with the help of TFIDF which is called vectorization.

Choosing a model: We can choose either Naive Bayes or Support Vector Machine.
Use naive bayes for classifying text data, it assumes that the features are independent and performs well on spam detection.
SVM is used to handles high dimensional text data. Its only demerit is it is computationally heavier but can achieve higher accuracy than naive bayes.

Handling class imbalance: To handle class imbalance we can use resampling techniques like: SMOTE or remove some non-spam emails, class weights(class_weight = 'balanced'), or threshold tuning like: adjusting the decision threshold to favour spam recall. We can use any one of the following technique to handle class imbalance.

Evaluation Metrics: For evaluating the performance of the model, use precision, recall, f1-score, roc-auc, confusion matrix from the sklearn.metrics module.

In building the model we should keep in mind that a false negative (missing the spam email) cannot harm much to the user than false positive(legit emails marked as spam).

Business Impact:
1. Employees spend less time filtering spam which can increase their productivity.
2. Users get fewer spam emails in their inbox leads to satisfaction of the customer.
3. Catching/ Phishing emails reduce the risk of data beaches.
4. Automated filtering reduces manual monitoring efforts.


In [12]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.datasets import load_iris, load_wine, load_breast_cancer
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.svm import SVC

import warnings
warnings.filterwarnings('ignore')

In [ ]:
#Question 6: Write a Python program to:
#● Load the Iris dataset
#● Train an SVM Classifier with a linear kernel
#● Print the model's accuracy and support vectors.
iris = load_iris()
x, y = iris.data, iris.target
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.30, random_state = 1)
clf = SVC(kernel = 'linear')
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
from sklearn.metrics import accuracy_score
print(f"The model accuracy is: {accuracy_score(y_test, y_pred)}")
print(f"The support vectors are: {clf.support_vectors_}")

The model accuracy is: 1.0
The support vectors are: [[5.1 3.3 1.7 0.5]
 [4.5 2.3 1.3 0.3]
 [4.8 3.4 1.9 0.2]
 [6.  3.4 4.5 1.6]
 [5.7 2.8 4.5 1.3]
 [6.  2.7 5.1 1.6]
 [6.9 3.1 4.9 1.5]
 [5.9 3.2 4.8 1.8]
 [4.9 2.4 3.3 1. ]
 [6.1 2.9 4.7 1.4]
 [6.7 3.1 4.7 1.5]
 [6.2 2.2 4.5 1.5]
 [6.3 2.5 4.9 1.5]
 [6.2 2.8 4.8 1.8]
 [6.3 2.7 4.9 1.8]
 [6.1 3.  4.9 1.8]
 [6.5 3.2 5.1 2. ]
 [6.  3.  4.8 1.8]
 [5.9 3.  5.1 1.8]
 [4.9 2.5 4.5 1.7]
 [7.2 3.  5.8 1.6]
 [6.3 2.8 5.1 1.5]]


In [7]:
#Question 7: Write a Python program to:
#● Load the Breast Cancer dataset
#● Train a Gaussian Naïve Bayes model
#● Print its classification report including precision, recall, and F1-score.
cancer = load_breast_cancer()
x, y = cancer.data, cancer.target

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 1)

from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.94      0.92      0.93        63
           1       0.95      0.96      0.96       108

    accuracy                           0.95       171
   macro avg       0.94      0.94      0.94       171
weighted avg       0.95      0.95      0.95       171



In [13]:
#Question 8: Write a Python program to:
#● Train an SVM Classifier on the Wine dataset using GridSearchCV to find the best
#C and gamma.
#● Print the best hyperparameters and accuracy.
wine = load_wine()
x, y  = wine.data, wine.target

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 1)

param = {
    'C': [0.1, 1, 10, 100],
    'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
    'kernel': ['rbf', 'polynomial']
}

svc = SVC()

grid = GridSearchCV(svc, param_grid = param, scoring = 'accuracy', cv = 5, verbose = 1)
grid.fit(x_train, y_train)
print(f"The best hyperparameters are: {grid.best_params_}")
print(f"The best accuracy is: {grid.best_score_}")

Fitting 5 folds for each of 40 candidates, totalling 200 fits
The best hyperparameters are: {'C': 100, 'gamma': 0.0001, 'kernel': 'rbf'}
The best accuracy is: 0.8463333333333333


In [19]:
#Question 9: Write a Python program to:
#● Train a Naïve Bayes Classifier on a synthetic text dataset (e.g. using
#sklearn.datasets.fetch_20newsgroups).
#● Print the model's ROC-AUC score for its predictions.
#data ingestion/ preprocessing
from sklearn.datasets import fetch_20newsgroups
newsgroups = fetch_20newsgroups(subset = 'all', categories = None)
categories = fetch_20newsgroups(subset = 'all').target_names
print("All categories in the dataset:")
for cat in categories:
    print(cat)
categorize = ['rec.motorcycles', 'sci.electronics', 'comp.graphics', 'talk.politics.mideast']
newsgroup = fetch_20newsgroups(subset = 'all', categories = categorize)
X, y = newsgroup.data, newsgroup.target

# convert text to numeric
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(X)

x_dense = X.toarray()

#train-test-split
x_train,x_test, y_train, y_test = train_test_split(x_dense, y, test_size = 0.25, random_state = 1)

#model training
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train, y_train)
y_prob = gnb.predict_proba(x_test)

# roc-auc score
from sklearn.metrics import roc_auc_score
roc_auc = roc_auc_score(y_test, y_prob, multi_class = 'ovr')
print(f"ROC-AUC Score : {roc_auc}")

All categories in the dataset:
alt.atheism
comp.graphics
comp.os.ms-windows.misc
comp.sys.ibm.pc.hardware
comp.sys.mac.hardware
comp.windows.x
misc.forsale
rec.autos
rec.motorcycles
rec.sport.baseball
rec.sport.hockey
sci.crypt
sci.electronics
sci.med
sci.space
soc.religion.christian
talk.politics.guns
talk.politics.mideast
talk.politics.misc
talk.religion.misc
ROC-AUC Score : 0.9691991749402641
